#!/usr/bin/env bash
#This script configures a server and adds a header indicating name of responding server
apt update && apt install nginx -y
echo 'Hello World!' > /var/www/html/index.html
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default

echo "add_header X-Served-By \$hostname;" > cus_headers.conf
mv cus_headers.conf /etc/nginx/conf.d/

service nginx reload
