#!/usr/bin/env bash
# This script prints to stdout indefinitely until a signal is detected
# With each specified signal it performs a specific action
echo $$ > /var/run/myscript.pid
trap "echo I hate the kill command; rm /var/run/myscript.pid; exit" SIGTERM 2> /dev/null
trap "echo Y U no love me?!; exit" SIGINT
trap "rm /var/run/myscript.pid; exit" SIGQUIT
until false
do
	echo To infinity and beyond
	sleep 0.1
done
