#!/usr/bin/env bash
# This script manages a background process
if [ $# -gt 1 ]
then
	echo "Usage: manage_my_process {start|stop|restart}"
	exit 1
fi

start()
{
	./manage_my_process &
	echo $! >> /var/run/my_process.pid
}

stop()
{
	kill "$(cat /var/run/my_process.pid)"
	rm -f /var/run/my_process.pid
}


case $1 in
	start)
		start
		echo manage_my_process started
		;;
	stop)
		stop
		echo manage_my_process stopped
		;;
	restart)
		stop
		start
		echo manage_my_process restarted
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
esac
