#!/usr/bin/env bash
#This script starts nginx web server as nginx user
chmod o+r /etc/nginx/nginx.conf
sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
