#!/usr/bin/env bash
#This script starts nginx web server as nginx user
chmod o+r /etc/nginx/nginx.conf
#sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80 /listen 8080 /g' /etc/nginx/sites-enabled/default
sed -i 's/:80 /listen :8080 /g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
