#!/usr/bin/env bash
#This script starts nginx web server as nginx user
chmod go+r /etc/nginx/nginx.conf
#sed -i "s/#user www-data;/user nginx;/" /etc/nginx/nginx.conf
sed -i "s/listen 80 /listen 8080 /g" /etc/nginx/sites-enabled/default
sed -i "s/:80 /:8080 /g" /etc/nginx/sites-enabled/default
kill "$(ps -aux | pgrep apache2 | head -n 1)"
sudo -u nginx service nginx start
